config/routes.rb
Rails.application.routes.draw do

  devise_for :users
resources :articles
=begin
      get "/articles" index
      post "/articles" create
      delete "/articles" delete
      get "/articles/:id" show
      get "/articles/new" new
      get "/articles/:id/edit" edit
      patch "/articles/:id" update
      put "/articles/:id" update
  end
=end

   root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	validates :title, presence: true
	validates :body, presence: true, length: { minimum: 20 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		@articles = Article.all
	end

	def show
		@article = Article.find(params[:id])
	end

	def new
		@article = Article.new
	end

	def edit
		@article = Article.find(params[:id])
	end

	def create
		#@article = Article.new(title: params[:article][:title], body: params[:article][:body])
		@article = Article.new(article_params)
		if @article.save
			redirect_to @article
		else
			render :new
		end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		redirect_to articles_path
	end
	def update
		@article = Article.find(params[:id])
		if @article.update(article_params)
			redirect_to @article
		else
			render :edit
		end
	end

	private

	def article_params
		params.require(:article).permit(:title,:body)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<% name ||= "Crear" %>
<h1><%= name %> artículo</h1>
<%= form_for(@article) do |f| %>
	<% @article.errors.full_messages.each do |message| %>
	<div class="be-red white top-space">
		* <%= message %>
	</div>
	<%end%>
	<div class="field">
		<%= f.text_field :title, placeholder: "Titulo", class:"form-control" %>
	</div>
	<div class="field">
		<%= f.text_area :body, placeholder: "Escribe aquí el artículo",style:"height:250px;", class:"form-control"  %>
	</div>
	<div class="field">
		<%= f.submit "Guardar", class:"btn be-red white" %>
	</div>
<%end%>

app/views/articles/edit.html.erb
<div style="width: 80%;margin:0 auto;">
	<%= render "form", name: "Editar" %>
</div>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
	<h1><%= link_to article.title, article %></h1>
	<div>
		<%= article.body %> - <%= link_to "Eliminar", article, mothod: :delete, class:"red" %>
	</div>
<% end %>

app/views/articles/new.html.erb
<div style="width: 80%;margin:0 auto;">
	<%= render "form" %>
</div>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<div>
	<%= @article.body %>
</div>
<div>
	<%= link_to "Editar", edit_article_path(@article) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,700,300' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <header>
        <nav class="be-red white large-padding">
            <ul class="no-list row center-xs middle-xs">
                <li class="col-md">
                    <h1 class="no-margin" id="logo">Blog Facilito</h1>
                </li>
                <li class="col-md">
                    <%= link_to "Inicio", root_path %>
                </li>
                <li class="col-md">
                    Diseño
                </li>
                <li class="col-md">
                    Programación
                </li>
                <li class="col-md">
                    Tecnologia
                </li>
                <% if  user_signed_in? %>
                    <li class="col-md">
                        <%= link_to "Cerrar sesión",  destroy_user_session_path, method: :delete %>
                    </li>
                <%end%>
            </ul>
        </nav>
    </header>
     <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Bienvenidos a Nuestro Blog!!</h1>